PW = ["Punta Cana", "America", "Canada", "Japan", "India"]
print(PW)
print(sorted(PW))
print(PW)
print(sorted(PW, reverse=True))
print(PW)
PW.reverse()
print(PW)
PW.reverse()
print(PW)
PW.sort()
print(PW)
PW.reverse()
print(PW)